### ISSUE TITLE
Initial todo

### ISSUE THREAD

**Issue by kwonoj** [kwonoj/docker-cld3-wasm#1]
- [x] setup submodule for cld3 / emscripten-protobuf
- [x] update makefile link config for protobuf into emscripten-protobuf
- [x] preprocessor
- [x] proof of concept code
- [x] asm.js?
