### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kwonoj** [kwonoj/docker-cld3-wasm#28]
- [ ] replace embind to idl (https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#webidl-binder)
- [ ] disable DYNAMIC_EXECUTION (https://github.com/emscripten-core/emscripten/blob/master/src/settings.js#L879)
- [ ] try above binary with CSP-enabled host (asm / wasm both)
